{
 "title": "Game stat",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total games played last 15 min",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(games_played_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Games by player",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "games_played_total", "legendFormat": "Player {{userId}}" }
   ]
  },
  {
   "title": "Coin Flip stats",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coin_flip_total{side=\"Heads\"}",
     "legendFormat": "{{side}}"
    },
    {
     "expr": "coin_flip_total{side=\"Tails\"}",
     "legendFormat": "{{side}}"
    }
   ]
  }
 ]
}